Update `six` in the remarshal tool for python3.12 compatibility
It's run in a repo rule, so it uses the system python.  Unfortunately.

The error seen is otherwise:

```
[nix-shell:~/work/dd_rules_poetry/tools]$ python3 --version
Python 3.12.2

[nix-shell:~/work/dd_rules_poetry/tools]$ ./remarshal.par
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/andrew.psaltis/work/dd_rules_poetry/tools/./remarshal.par/__main__.py", line 6, in <module>
  File "/Users/andrew.psaltis/work/dd_rules_poetry/tools/./remarshal.par/pypi__remarshal_0_10_0/remarshal.py", line 10, in <module>
  File "/Users/andrew.psaltis/work/dd_rules_poetry/tools/./remarshal.par/pypi__python_dateutil_2_8_0/dateutil/parser/__init__.py", line 2, in <module>
  File "/Users/andrew.psaltis/work/dd_rules_poetry/tools/./remarshal.par/pypi__python_dateutil_2_8_0/dateutil/parser/_parser.py", line 50, in <module>
  File "/Users/andrew.psaltis/work/dd_rules_poetry/tools/./remarshal.par/pypi__python_dateutil_2_8_0/dateutil/tz/__init__.py", line 2, in <module>
  File "/Users/andrew.psaltis/work/dd_rules_poetry/tools/./remarshal.par/pypi__python_dateutil_2_8_0/dateutil/tz/tz.py", line 21, in <module>
ModuleNotFoundError: No module named 'six.moves'
```